// <auto-generated />
using System;
using Clutch.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clutch.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clutch.Database.Entities.Blobs.Blob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blobs");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Clips.Clip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ExternalVideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastCounterUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<int>("SaveCount")
                        .HasColumnType("int");

                    b.Property<int>("ShareCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GameId");

                    b.ToTable("Clips");
                });

            modelBuilder.Entity("Clutch.Database.Entities.CommentLikes.CommentLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("InitiatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("UserId");

                    b.HasIndex("InitiatorUserId", "CommentId")
                        .IsUnique();

                    b.ToTable("CommentLikes");
                });

            modelBuilder.Entity("Clutch.Database.Entities.CommentThreads.CommentThread", b =>
                {
                    b.Property<int>("ClipId")
                        .HasColumnType("int");

                    b.HasKey("ClipId");

                    b.ToTable("CommentThreads");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Comments.Comment", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrowserLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<int>("CommentThreadId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevicePlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LikeCount")
                        .HasColumnType("int");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("int");

                    b.Property<long?>("RootCommentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UserIsLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("AuthorId");

                    b.HasIndex("CommentId");

                    b.HasIndex("CommentThreadId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("RootCommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Clutch.Database.Entities.ContestWinners.ContestWinner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClipId")
                        .HasColumnType("int");

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("Placement")
                        .HasColumnType("int");

                    b.Property<decimal>("PrizeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.HasIndex("ContestId");

                    b.ToTable("ContestWinners");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Contests.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("datetimeoffset");

                    b.PrimitiveCollection<string>("Sponsors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SubmissionCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("int");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("Clutch.Database.Entities.DirectMessages.DirectMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DirectThreadId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DirectThreadId");

                    b.ToTable("DirectMessages");
                });

            modelBuilder.Entity("Clutch.Database.Entities.DirectThreads.DirectThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasNewUnreadMessage")
                        .HasColumnType("bit");

                    b.Property<string>("LastMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ParticipantAId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("ParticipantALastReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ParticipantBId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("ParticipantBLastReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantBId");

                    b.HasIndex("UserId");

                    b.HasIndex("ParticipantAId", "ParticipantBId")
                        .IsUnique();

                    b.ToTable("DirectThreads");
                });

            modelBuilder.Entity("Clutch.Database.Entities.EventConsumerOffset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumerGroup")
                        .HasColumnType("int");

                    b.Property<int>("LastProcessedEventId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EventConsumerOffsets");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Follows.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("InitiatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("InitiatorUserId", "TargetUserId")
                        .IsUnique();

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Games.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Clutch.Database.Entities.InboxActivities.InboxActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CommentLikeId")
                        .HasColumnType("int");

                    b.Property<string>("DestinationUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FollowId")
                        .HasColumnType("int");

                    b.Property<string>("InitiatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LikeId")
                        .HasColumnType("int");

                    b.Property<int?>("MentionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserInboxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CommentId")
                        .IsUnique()
                        .HasFilter("[CommentId] IS NOT NULL");

                    b.HasIndex("CommentLikeId")
                        .IsUnique()
                        .HasFilter("[CommentLikeId] IS NOT NULL");

                    b.HasIndex("FollowId")
                        .IsUnique()
                        .HasFilter("[FollowId] IS NOT NULL");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("LikeId")
                        .IsUnique()
                        .HasFilter("[LikeId] IS NOT NULL");

                    b.HasIndex("MentionId")
                        .IsUnique()
                        .HasFilter("[MentionId] IS NOT NULL");

                    b.HasIndex("UserInboxId");

                    b.ToTable("InboxActivities");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Likes.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrowserLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClipId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevicePlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UserIsLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.HasIndex("AuthorId", "ClipId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Mentions.Mention", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("InitiatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Mentions");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Saves.Save", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrowserLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClipId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevicePlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UserIsLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.HasIndex("AuthorId", "ClipId")
                        .IsUnique();

                    b.ToTable("Saves");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Shares.Share", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrowserLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClipId")
                        .HasColumnType("int");

                    b.Property<int>("Destination")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevicePlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UserIsLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.HasIndex("AuthorId", "ClipId");

                    b.ToTable("Shares");
                });

            modelBuilder.Entity("Clutch.Database.Entities.StagingClips.StagingClip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GameId");

                    b.ToTable("StagingClips");
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserEvents.UserEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("BrowserLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevicePlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UserIsLoggedIn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserInboxes.UserInbox", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UnseenClipLikeCount")
                        .HasColumnType("int");

                    b.Property<int>("UnseenCommentClipCount")
                        .HasColumnType("int");

                    b.Property<int>("UnseenCommentLikeCount")
                        .HasColumnType("int");

                    b.Property<int>("UnseenCommentReplyCount")
                        .HasColumnType("int");

                    b.Property<int>("UnseenDirectMessageCount")
                        .HasColumnType("int");

                    b.Property<int>("UnseenUserFollowCount")
                        .HasColumnType("int");

                    b.Property<int>("UnseenUserMentionCount")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("UserInboxes");
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserWallets.UserWallet", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalEarned")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId");

                    b.ToTable("UserWallet");
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserWallets.WithdrawalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Destination")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserWalletId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserWalletId");

                    b.ToTable("WithdrawalRequest");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("int");

                    b.Property<int>("FollowingCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsLoggedIn")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastLoginDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileBio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Clutch.Database.Entities.Views.View", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrowserLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClipId")
                        .HasColumnType("int");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevicePlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Muted")
                        .HasColumnType("bit");

                    b.Property<decimal>("PercentViewed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReplayCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UserIsLoggedIn")
                        .HasColumnType("bit");

                    b.Property<double>("ViewDurationInSeconds")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClipId");

                    b.HasIndex("AuthorId", "ClipId");

                    b.ToTable("Views");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clutch.Database.Entities.Clips.Clip", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "Author")
                        .WithMany("Clips")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Games.Game", "Game")
                        .WithMany("Clips")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Clutch.Database.Entities.Clips.ClipMedia", "Media", b1 =>
                        {
                            b1.Property<int>("ClipId")
                                .HasColumnType("int");

                            b1.HasKey("ClipId");

                            b1.ToTable("Clips");

                            b1.WithOwner()
                                .HasForeignKey("ClipId");

                            b1.OwnsOne("BlobReference", "Avatar", b2 =>
                                {
                                    b2.Property<int>("ClipMediaClipId")
                                        .HasColumnType("int");

                                    b2.Property<string>("BlobName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ContainerName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ClipMediaClipId");

                                    b2.ToTable("Clips");

                                    b2.WithOwner()
                                        .HasForeignKey("ClipMediaClipId");
                                });

                            b1.OwnsOne("BlobReference", "OriginalUpload", b2 =>
                                {
                                    b2.Property<int>("ClipMediaClipId")
                                        .HasColumnType("int");

                                    b2.Property<string>("BlobName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ContainerName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ClipMediaClipId");

                                    b2.ToTable("Clips");

                                    b2.WithOwner()
                                        .HasForeignKey("ClipMediaClipId");
                                });

                            b1.OwnsOne("BlobReference", "Resolution1080p", b2 =>
                                {
                                    b2.Property<int>("ClipMediaClipId")
                                        .HasColumnType("int");

                                    b2.Property<string>("BlobName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ContainerName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ClipMediaClipId");

                                    b2.ToTable("Clips");

                                    b2.WithOwner()
                                        .HasForeignKey("ClipMediaClipId");
                                });

                            b1.OwnsOne("BlobReference", "Resolution144p", b2 =>
                                {
                                    b2.Property<int>("ClipMediaClipId")
                                        .HasColumnType("int");

                                    b2.Property<string>("BlobName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ContainerName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ClipMediaClipId");

                                    b2.ToTable("Clips");

                                    b2.WithOwner()
                                        .HasForeignKey("ClipMediaClipId");
                                });

                            b1.OwnsOne("BlobReference", "Resolution240p", b2 =>
                                {
                                    b2.Property<int>("ClipMediaClipId")
                                        .HasColumnType("int");

                                    b2.Property<string>("BlobName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ContainerName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ClipMediaClipId");

                                    b2.ToTable("Clips");

                                    b2.WithOwner()
                                        .HasForeignKey("ClipMediaClipId");
                                });

                            b1.OwnsOne("BlobReference", "Resolution360p", b2 =>
                                {
                                    b2.Property<int>("ClipMediaClipId")
                                        .HasColumnType("int");

                                    b2.Property<string>("BlobName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ContainerName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ClipMediaClipId");

                                    b2.ToTable("Clips");

                                    b2.WithOwner()
                                        .HasForeignKey("ClipMediaClipId");
                                });

                            b1.OwnsOne("BlobReference", "Resolution480p", b2 =>
                                {
                                    b2.Property<int>("ClipMediaClipId")
                                        .HasColumnType("int");

                                    b2.Property<string>("BlobName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ContainerName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ClipMediaClipId");

                                    b2.ToTable("Clips");

                                    b2.WithOwner()
                                        .HasForeignKey("ClipMediaClipId");
                                });

                            b1.OwnsOne("BlobReference", "Resolution720p", b2 =>
                                {
                                    b2.Property<int>("ClipMediaClipId")
                                        .HasColumnType("int");

                                    b2.Property<string>("BlobName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("ContainerName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ClipMediaClipId");

                                    b2.ToTable("Clips");

                                    b2.WithOwner()
                                        .HasForeignKey("ClipMediaClipId");
                                });

                            b1.Navigation("Avatar")
                                .IsRequired();

                            b1.Navigation("OriginalUpload")
                                .IsRequired();

                            b1.Navigation("Resolution1080p");

                            b1.Navigation("Resolution144p");

                            b1.Navigation("Resolution240p");

                            b1.Navigation("Resolution360p");

                            b1.Navigation("Resolution480p");

                            b1.Navigation("Resolution720p");
                        });

                    b.Navigation("Author");

                    b.Navigation("Game");

                    b.Navigation("Media")
                        .IsRequired();
                });

            modelBuilder.Entity("Clutch.Database.Entities.CommentLikes.CommentLike", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Comments.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Users.User", "InitiatorUser")
                        .WithMany("CommentLikesReceived")
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Users.User", null)
                        .WithMany("CommentsLiked")
                        .HasForeignKey("UserId");

                    b.Navigation("Comment");

                    b.Navigation("InitiatorUser");
                });

            modelBuilder.Entity("Clutch.Database.Entities.CommentThreads.CommentThread", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Clips.Clip", "Clip")
                        .WithOne("CommentThread")
                        .HasForeignKey("Clutch.Database.Entities.CommentThreads.CommentThread", "ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Comments.Comment", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Comments.Comment", null)
                        .WithMany("Replies")
                        .HasForeignKey("CommentId");

                    b.HasOne("Clutch.Database.Entities.CommentThreads.CommentThread", "CommentThread")
                        .WithMany("Comments")
                        .HasForeignKey("CommentThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Comments.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clutch.Database.Entities.Comments.Comment", "RootComment")
                        .WithMany()
                        .HasForeignKey("RootCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Author");

                    b.Navigation("CommentThread");

                    b.Navigation("ParentComment");

                    b.Navigation("RootComment");
                });

            modelBuilder.Entity("Clutch.Database.Entities.ContestWinners.ContestWinner", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Clips.Clip", "Clip")
                        .WithMany("ContestWins")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Contests.Contest", "Contest")
                        .WithMany("Winners")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clip");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("Clutch.Database.Entities.DirectMessages.DirectMessage", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.DirectThreads.DirectThread", "DirectThread")
                        .WithMany("Messages")
                        .HasForeignKey("DirectThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("DirectThread");
                });

            modelBuilder.Entity("Clutch.Database.Entities.DirectThreads.DirectThread", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "ParticipantA")
                        .WithMany()
                        .HasForeignKey("ParticipantAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Users.User", "ParticipantB")
                        .WithMany()
                        .HasForeignKey("ParticipantBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Users.User", null)
                        .WithMany("DirectThreads")
                        .HasForeignKey("UserId");

                    b.Navigation("ParticipantA");

                    b.Navigation("ParticipantB");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Follows.Follow", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "InitiatorUser")
                        .WithMany("FollowsReceived")
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Users.User", "TargetUser")
                        .WithMany("FollowsMade")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InitiatorUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Clutch.Database.Entities.InboxActivities.InboxActivity", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Comments.Comment", "Comment")
                        .WithOne("InboxActivity")
                        .HasForeignKey("Clutch.Database.Entities.InboxActivities.InboxActivity", "CommentId");

                    b.HasOne("Clutch.Database.Entities.CommentLikes.CommentLike", "CommentLike")
                        .WithOne("InboxActivity")
                        .HasForeignKey("Clutch.Database.Entities.InboxActivities.InboxActivity", "CommentLikeId");

                    b.HasOne("Clutch.Database.Entities.Follows.Follow", "Follow")
                        .WithOne("InboxActivity")
                        .HasForeignKey("Clutch.Database.Entities.InboxActivities.InboxActivity", "FollowId");

                    b.HasOne("Clutch.Database.Entities.Users.User", "Initiator")
                        .WithMany("InitiatedActivities")
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Likes.Like", "Like")
                        .WithOne("InboxActivity")
                        .HasForeignKey("Clutch.Database.Entities.InboxActivities.InboxActivity", "LikeId");

                    b.HasOne("Clutch.Database.Entities.Mentions.Mention", "Mention")
                        .WithOne("InboxActivity")
                        .HasForeignKey("Clutch.Database.Entities.InboxActivities.InboxActivity", "MentionId");

                    b.HasOne("Clutch.Database.Entities.UserInboxes.UserInbox", "UserInbox")
                        .WithMany("Activities")
                        .HasForeignKey("UserInboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("CommentLike");

                    b.Navigation("Follow");

                    b.Navigation("Initiator");

                    b.Navigation("Like");

                    b.Navigation("Mention");

                    b.Navigation("UserInbox");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Likes.Like", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "Author")
                        .WithMany("Likes")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Clips.Clip", "Clip")
                        .WithMany("Likes")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Mentions.Mention", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "InitiatorUser")
                        .WithMany("MentionsMade")
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Users.User", "TargetUser")
                        .WithMany("MentionsReceived")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InitiatorUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Saves.Save", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "Author")
                        .WithMany("Saves")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Clips.Clip", "Clip")
                        .WithMany("Saves")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Shares.Share", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "Author")
                        .WithMany("Shares")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Clips.Clip", "Clip")
                        .WithMany("Shares")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("Clutch.Database.Entities.StagingClips.StagingClip", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Games.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BlobReference", "BlobReference", b1 =>
                        {
                            b1.Property<int>("StagingClipId")
                                .HasColumnType("int");

                            b1.Property<string>("BlobName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ContainerName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StagingClipId");

                            b1.ToTable("StagingClips");

                            b1.WithOwner()
                                .HasForeignKey("StagingClipId");
                        });

                    b.Navigation("Author");

                    b.Navigation("BlobReference")
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserEvents.UserEvent", b =>
                {
                    b.OwnsOne("Clutch.Database.Entities.UserEvents.LikeEventData", "LikeEvent", b1 =>
                        {
                            b1.Property<int>("UserEventId")
                                .HasColumnType("int");

                            b1.Property<string>("AuthorId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BrowserLanguage")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ClipId")
                                .HasColumnType("int");

                            b1.Property<string>("DeviceId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DevicePlatform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<bool>("UserIsLoggedIn")
                                .HasColumnType("bit");

                            b1.HasKey("UserEventId");

                            b1.ToTable("UserEvent_LikeEvent", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserEventId");
                        });

                    b.OwnsOne("CommentEventData", "CommentEvent", b1 =>
                        {
                            b1.Property<int>("UserEventId")
                                .HasColumnType("int");

                            b1.Property<string>("AuthorId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BrowserLanguage")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long>("CommentId")
                                .HasColumnType("bigint");

                            b1.Property<int>("CommentThreadId")
                                .HasColumnType("int");

                            b1.Property<string>("DeviceId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DevicePlatform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long?>("ParentCommentId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long?>("RootCommentId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<bool>("UserIsLoggedIn")
                                .HasColumnType("bit");

                            b1.HasKey("UserEventId");

                            b1.ToTable("UserEvent_CommentEvent", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserEventId");
                        });

                    b.OwnsOne("CommentLikeEventData", "CommentLikeEvent", b1 =>
                        {
                            b1.Property<int>("UserEventId")
                                .HasColumnType("int");

                            b1.Property<long>("CommentId")
                                .HasColumnType("bigint");

                            b1.Property<string>("InitiatorUserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("UserEventId");

                            b1.ToTable("UserEvent_CommentLikeEvent", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserEventId");
                        });

                    b.OwnsOne("FollowEventData", "FollowEvent", b1 =>
                        {
                            b1.Property<int>("UserEventId")
                                .HasColumnType("int");

                            b1.Property<string>("InitiatorUserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TargetUserId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("UserEventId");

                            b1.ToTable("UserEvent_FollowEvent", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserEventId");
                        });

                    b.OwnsOne("SaveEventData", "SaveEvent", b1 =>
                        {
                            b1.Property<int>("UserEventId")
                                .HasColumnType("int");

                            b1.Property<string>("AuthorId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BrowserLanguage")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ClipId")
                                .HasColumnType("int");

                            b1.Property<string>("DeviceId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DevicePlatform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("datetimeoffset");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<bool>("UserIsLoggedIn")
                                .HasColumnType("bit");

                            b1.HasKey("UserEventId");

                            b1.ToTable("UserEvent_SaveEvent", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserEventId");
                        });

                    b.OwnsOne("ShareEventData", "ShareEvent", b1 =>
                        {
                            b1.Property<int>("UserEventId")
                                .HasColumnType("int");

                            b1.Property<string>("AuthorId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BrowserLanguage")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ClipId")
                                .HasColumnType("int");

                            b1.Property<int>("Destination")
                                .HasColumnType("int");

                            b1.Property<string>("DeviceId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DevicePlatform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("datetimeoffset");

                            b1.Property<bool>("UserIsLoggedIn")
                                .HasColumnType("bit");

                            b1.HasKey("UserEventId");

                            b1.ToTable("UserEvent_ShareEvent", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserEventId");
                        });

                    b.OwnsOne("ViewEventData", "ViewEvent", b1 =>
                        {
                            b1.Property<int>("UserEventId")
                                .HasColumnType("int");

                            b1.Property<string>("AuthorId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("BrowserLanguage")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ClipId")
                                .HasColumnType("int");

                            b1.Property<string>("DeviceId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DevicePlatform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("Muted")
                                .HasColumnType("bit");

                            b1.Property<decimal>("PercentViewed")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Platform")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ReplayCount")
                                .HasColumnType("int");

                            b1.Property<DateTimeOffset>("Timestamp")
                                .HasColumnType("datetimeoffset");

                            b1.Property<bool>("UserIsLoggedIn")
                                .HasColumnType("bit");

                            b1.Property<double>("ViewDurationInSeconds")
                                .HasColumnType("float");

                            b1.HasKey("UserEventId");

                            b1.ToTable("UserEvent_ViewEvent", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserEventId");
                        });

                    b.Navigation("CommentEvent");

                    b.Navigation("CommentLikeEvent");

                    b.Navigation("FollowEvent");

                    b.Navigation("LikeEvent");

                    b.Navigation("SaveEvent");

                    b.Navigation("ShareEvent");

                    b.Navigation("ViewEvent");
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserInboxes.UserInbox", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "User")
                        .WithOne("UserInbox")
                        .HasForeignKey("Clutch.Database.Entities.UserInboxes.UserInbox", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserWallets.UserWallet", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Clutch.Database.Entities.UserWallets.UserWallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserWallets.WithdrawalRequest", b =>
                {
                    b.HasOne("Clutch.Database.Entities.UserWallets.UserWallet", "UserWallet")
                        .WithMany("WithdrawalRequests")
                        .HasForeignKey("UserWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserWallet");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Views.View", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", "Author")
                        .WithMany("Views")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Clutch.Database.Entities.Clips.Clip", "Clip")
                        .WithMany("Views")
                        .HasForeignKey("ClipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Clip");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clutch.Database.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Clutch.Database.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clutch.Database.Entities.Clips.Clip", b =>
                {
                    b.Navigation("CommentThread")
                        .IsRequired();

                    b.Navigation("ContestWins");

                    b.Navigation("Likes");

                    b.Navigation("Saves");

                    b.Navigation("Shares");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("Clutch.Database.Entities.CommentLikes.CommentLike", b =>
                {
                    b.Navigation("InboxActivity")
                        .IsRequired();
                });

            modelBuilder.Entity("Clutch.Database.Entities.CommentThreads.CommentThread", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Comments.Comment", b =>
                {
                    b.Navigation("InboxActivity")
                        .IsRequired();

                    b.Navigation("Likes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Contests.Contest", b =>
                {
                    b.Navigation("Winners");
                });

            modelBuilder.Entity("Clutch.Database.Entities.DirectThreads.DirectThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Follows.Follow", b =>
                {
                    b.Navigation("InboxActivity")
                        .IsRequired();
                });

            modelBuilder.Entity("Clutch.Database.Entities.Games.Game", b =>
                {
                    b.Navigation("Clips");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Likes.Like", b =>
                {
                    b.Navigation("InboxActivity")
                        .IsRequired();
                });

            modelBuilder.Entity("Clutch.Database.Entities.Mentions.Mention", b =>
                {
                    b.Navigation("InboxActivity")
                        .IsRequired();
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserInboxes.UserInbox", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("Clutch.Database.Entities.UserWallets.UserWallet", b =>
                {
                    b.Navigation("WithdrawalRequests");
                });

            modelBuilder.Entity("Clutch.Database.Entities.Users.User", b =>
                {
                    b.Navigation("Clips");

                    b.Navigation("CommentLikesReceived");

                    b.Navigation("Comments");

                    b.Navigation("CommentsLiked");

                    b.Navigation("DirectThreads");

                    b.Navigation("FollowsMade");

                    b.Navigation("FollowsReceived");

                    b.Navigation("InitiatedActivities");

                    b.Navigation("Likes");

                    b.Navigation("MentionsMade");

                    b.Navigation("MentionsReceived");

                    b.Navigation("Saves");

                    b.Navigation("Shares");

                    b.Navigation("UserInbox")
                        .IsRequired();

                    b.Navigation("Views");

                    b.Navigation("Wallet")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
